points:
  zones:
    matrix:
      anchor:
        rotate: 12
      columns:
        pinky:
          rows:
            top:
              bind: [1,40,0,1.5]
              column_net: P4
            home:
              bind: [0,40,0,1.5]
              column_net: P5
            bottom:
              bind: [0,50,1,1.5]
              column_net: P6
        ring:
          rotate: -12
          origin: [-12, -19]
          stagger: 12
          rows:
            top:
              bind: [1,0,0,1.5]
              column_net: P7
            home:
              bind: [0,0,0,0]
              column_net: P8
            bottom:
              bind: [0,0,0,0]
              column_net: P9
        middle:
          stagger: 8
          rows:
            top:
              bind: [1,1.5,0,1.5]
              column_net: P14
            home:
              bind: [0,1,0,0]
              column_net: P16
            bottom:
              bind: [0,1,0,0]
              column_net: P10
        index:
          stagger: -12
          rows:
            top:
              bind: [1,48,0,0]
              column_net: P0
            home:
              bind: [0,48,0,0]
              column_net: P21
            bottom:
              bind: [0,48,0,0]
              column_net: P20
        inner:
          stagger: -4
          rows:
            top:
              bind: [0,0,0,0]
              column_net: P19
            home:
              bind: [0,0,0,0]
              column_net: P18
            bottom:
              bind: [0,0,3,50]
              column_net: P15
      rows:
        bottom:
        home:
        top:
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [24, -10]
      columns:
        near:
          rotate: -20
          rows:
            thumb:
              bind: [0,0,1,50]
              column_net: P3
        home:
          spread: 19
          rotate: -24
          origin: [-10, -9]
          rows:
            thumb:
              bind: [1,1.5,1,20]
              column_net: P2
      rows:
        thumb:
  key:
    padding: cy
    footprints:
      choc_hotswap:
        type: choc
        nets:
          from: =column_net
          to: GND
        params:
          keycaps: true
          reverse: true
          hotswap: true
      choc:
        type: choc
        anchor:
          rotate: 180
        nets:
          from: =column_net
          to: GND
        params:
          keycaps: true
          reverse: true
outlines:
  exports:
    raw:
      - type: keys
        side: left
        size: [1cx, 1cx]
    cutout:
      - type: outline
        name: raw
        fillet: 1
    keycap_outlines:
      - type: keys
        side: left
        size: [1cx - 0.5, 1cy - 0.5] # Choc keycaps are 17.5 x 16.5
        bound: false
pcbs:
  main:
    outlines:
      main:
        outline: cutout
    footprints:
      promicro:
        type: promicro
        anchor:
          ref: matrix_inner_top
          shift: [20, -5.3]
          rotate: -90
        params:
          orientation: down
      trrs:
        type: trrs
        anchor:
          ref: matrix_inner_top
          shift: [36, 12]
          rotate: 0
        nets:
          A: GND
          B: GND
          C: P1
          D: VCC
        params:
          reverse: true
          symmetric: true
